export const applications = [
  {
    id: "1",
    company: "Nordcloud",
    position: "Frontend Developer",
    location: "Poland",
    workMode: "remote",
    status: "interview",
    appliedAt: "2026-09-08",
    nextStep: "Technical",
    nextStepDate: "2026-09-12",
  },
  {
    id: "2",
    company: "Allegro",
    position: "React Developer",
    location: "Gdańsk",
    workMode: "hybrid",
    status: "applied",
    appliedAt: "2026-09-06",
    nextStep: "Follow up",
    nextStepDate: "2026-09-13",
  },
  {
    id: "3",
    company: "Docplanner",
    position: "Frontend Engineer",
    location: "EU",
    workMode: "remote",
    status: "offer",
    appliedAt: "2026-08-28",
    nextStep: "Reply",
    nextStepDate: "2026-09-11",
  },
  {
    id: "4",
    company: "AirHelp",
    position: "UI Developer",
    location: "Gdańsk",
    workMode: "hybrid",
    status: "rejected",
    appliedAt: "2026-08-22",
    nextStep: null,
    nextStepDate: null,
  },
  {
    id: "5",
    company: "Booksy",
    position: "Frontend Developer",
    location: "Warsaw",
    workMode: "hybrid",
    status: "applied",
    appliedAt: "2026-09-05",
    nextStep: "Follow up",
    nextStepDate: "2026-09-15",
  },
  {
    id: "6",
    company: "Netguru",
    position: "React Developer",
    location: "Remote",
    workMode: "remote",
    status: "interview",
    appliedAt: "2026-09-01",
    nextStep: "HR call",
    nextStepDate: "2026-09-14",
  },
  {
    id: "7",
    company: "Brainly",
    position: "Frontend Engineer",
    location: "Kraków",
    workMode: "hybrid",
    status: "applied",
    appliedAt: "2026-09-10",
    nextStep: "Awaiting response",
    nextStepDate: null,
  },
  {
    id: "8",
    company: "Vercel",
    position: "UI Engineer",
    location: "Remote",
    workMode: "remote",
    status: "rejected",
    appliedAt: "2026-08-15",
    nextStep: null,
    nextStepDate: null,
  },
  {
    id: "9",
    company: "Livechat",
    position: "Frontend Developer",
    location: "Wrocław",
    workMode: "hybrid",
    status: "interview",
    appliedAt: "2026-09-03",
    nextStep: "Final round",
    nextStepDate: "2026-09-16",
  },
  {
    id: "10",
    company: "Ramp Network",
    position: "React Developer",
    location: "Warsaw",
    workMode: "hybrid",
    status: "offer",
    appliedAt: "2026-08-25",
    nextStep: "Negotiate offer",
    nextStepDate: "2026-09-13",
  },
  {
    id: "11",
    company: "Packhelp",
    position: "Frontend Developer",
    location: "Warsaw",
    workMode: "onsite",
    status: "applied",
    appliedAt: "2026-09-09",
    nextStep: "Awaiting response",
    nextStepDate: null,
  },
  {
    id: "12",
    company: "Preply",
    position: "React Developer",
    location: "Remote",
    workMode: "remote",
    status: "interview",
    appliedAt: "2026-08-30",
    nextStep: "Technical",
    nextStepDate: "2026-09-17",
  },
];
